DROP TABLE IF EXISTS crime_scene_reports;
CREATE TABLE crime_scene_reports(
   id          INTEGER  NOT NULL PRIMARY KEY 
  ,year        INTEGER  NOT NULL
  ,month       INTEGER  NOT NULL
  ,day         INTEGER  NOT NULL
  ,description VARCHAR(255) NOT NULL
);
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (1,2020,6,1,'Credit card fraud took place at 00:53. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (2,2020,6,1,'Burglary took place at 05:23. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (3,2020,6,1,'Shoplifting took place at 20:48. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (4,2020,6,1,'Jaywalking took place at 23:37. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (5,2020,6,2,'Jaywalking took place at 20:33. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (6,2020,6,3,'Insider trading took place at 19:32. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (7,2020,6,3,'Theft took place at 20:49. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (8,2020,6,4,'Bank robbery took place at 10:32. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (9,2020,6,4,'Money laundering took place at 05:26. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (10,2020,6,5,'Insider trading took place at 05:13. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (11,2020,6,5,'Credit card fraud took place at 21:35. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (12,2020,6,5,'Littering took place at 04:18. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (13,2020,6,6,'Reckless driving took place at 07:18. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (14,2020,6,6,'Insider trading took place at 11:35. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (15,2020,6,7,'Shoplifting took place at 11:42. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (16,2020,6,7,'Credit card fraud took place at 14:47. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (17,2020,6,7,'Credit card fraud took place at 03:14. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (18,2020,6,8,'Jaywalking took place at 10:04. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (19,2020,6,8,'Bank robbery took place at 15:30. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (20,2020,6,8,'Credit card fraud took place at 13:40. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (21,2020,6,9,'Expired parking meter took place at 01:53. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (22,2020,6,10,'Theft took place at 16:16. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (23,2020,6,10,'Theft took place at 01:15. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (24,2020,6,11,'Shoplifting took place at 13:23. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (25,2020,6,11,'Wire fraud took place at 10:38. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (26,2020,6,11,'Forgery took place at 23:28. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (27,2020,6,12,'Theft took place at 16:51. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (28,2020,6,12,'Burglary took place at 12:57. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (29,2020,6,13,'Credit card fraud took place at 11:12. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (30,2020,6,13,'Expired parking meter took place at 22:55. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (31,2020,6,16,'Vandalism took place at 16:41. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (32,2020,6,17,'Insider trading took place at 23:24. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (33,2020,6,17,'Littering took place at 05:46. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (34,2020,6,17,'Reckless driving took place at 00:52. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (35,2020,6,17,'Money laundering took place at 22:49. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (36,2020,6,17,'Jaywalking took place at 21:38. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (37,2020,6,17,'Vandalism took place at 04:51. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (38,2020,6,20,'Wire fraud took place at 10:31. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (39,2020,6,20,'Burglary took place at 02:22. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (40,2020,6,21,'Shoplifting took place at 22:02. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (41,2020,6,22,'Wire fraud took place at 15:42. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (42,2020,6,23,'Expired parking meter took place at 09:47. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (43,2020,6,24,'Burglary took place at 10:53. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (44,2020,6,25,'Jaywalking took place at 08:53. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (45,2020,6,27,'Money laundering took place at 19:53. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (46,2020,6,27,'Forgery took place at 05:50. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (47,2020,6,28,'Bank robbery took place at 09:43. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (48,2020,6,28,'Bank robbery took place at 09:13. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (49,2020,7,1,'Theft took place at 03:25. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (50,2020,7,1,'Money laundering took place at 15:48. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (51,2020,7,2,'Insider trading took place at 08:46. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (52,2020,7,4,'Wire fraud took place at 23:32. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (53,2020,7,4,'Vandalism took place at 07:57. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (54,2020,7,4,'Credit card fraud took place at 07:43. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (55,2020,7,4,'Expired parking meter took place at 02:26. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (56,2020,7,4,'Money laundering took place at 23:18. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (57,2020,7,5,'Jaywalking took place at 21:43. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (58,2020,7,5,'Expired parking meter took place at 03:21. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (59,2020,7,6,'Littering took place at 20:58. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (60,2020,7,6,'Forgery took place at 12:24. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (61,2020,7,7,'Expired parking meter took place at 06:30. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (62,2020,7,8,'Insider trading took place at 05:43. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (63,2020,7,8,'Littering took place at 05:09. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (64,2020,7,9,'Vandalism took place at 18:19. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (65,2020,7,11,'Insider trading took place at 13:14. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (66,2020,7,12,'Vandalism took place at 18:15. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (67,2020,7,14,'Money laundering took place at 12:35. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (68,2020,7,15,'Bank robbery took place at 08:49. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (69,2020,7,16,'Bank robbery took place at 21:41. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (70,2020,7,17,'Shoplifting took place at 10:27. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (71,2020,7,19,'Theft took place at 11:54. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (72,2020,7,19,'Jaywalking took place at 01:40. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (73,2020,7,20,'Wire fraud took place at 04:55. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (74,2020,7,20,'Wire fraud took place at 18:37. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (75,2020,7,22,'Credit card fraud took place at 01:32. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (76,2020,7,22,'Shoplifting took place at 06:11. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (77,2020,7,22,'Credit card fraud took place at 12:26. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (78,2020,7,25,'Burglary took place at 13:08. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (79,2020,7,25,'Bank robbery took place at 04:05. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (80,2020,7,26,'Theft took place at 03:11. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (81,2020,7,26,'Insider trading took place at 14:06. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (82,2020,7,27,'Money laundering took place at 17:54. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (83,2020,7,28,'Reckless driving took place at 22:02. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (84,2020,7,28,'Forgery took place at 21:34. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (85,2020,7,28,'Wire fraud took place at 01:22. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (86,2020,8,1,'Insider trading took place at 17:19. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (87,2020,8,2,'Littering took place at 07:40. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (88,2020,8,2,'Credit card fraud took place at 22:11. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (89,2020,8,4,'Reckless driving took place at 21:04. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (90,2020,8,4,'Wire fraud took place at 11:48. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (91,2020,8,5,'Bank robbery took place at 07:46. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (92,2020,8,5,'Forgery took place at 21:10. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (93,2020,8,5,'Jaywalking took place at 08:07. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (94,2020,8,5,'Forgery took place at 06:31. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (95,2020,8,8,'Burglary took place at 20:14. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (96,2020,8,8,'Burglary took place at 23:15. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (97,2020,8,10,'Theft took place at 14:39. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (98,2020,8,10,'Littering took place at 16:46. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (99,2020,8,11,'Jaywalking took place at 11:51. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (100,2020,8,11,'Vandalism took place at 14:47. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (101,2020,8,12,'Theft took place at 18:55. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (102,2020,8,13,'Theft took place at 09:36. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (103,2020,8,14,'Wire fraud took place at 15:08. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (104,2020,8,15,'Bank robbery took place at 12:38. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (105,2020,8,16,'Insider trading took place at 23:10. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (106,2020,8,16,'Jaywalking took place at 20:07. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (107,2020,8,16,'Jaywalking took place at 01:49. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (108,2020,8,17,'Bank robbery took place at 22:39. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (109,2020,8,18,'Jaywalking took place at 09:21. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (110,2020,8,18,'Littering took place at 02:17. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (111,2020,8,20,'Credit card fraud took place at 23:37. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (112,2020,8,20,'Vandalism took place at 08:39. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (113,2020,8,20,'Credit card fraud took place at 08:41. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (114,2020,8,21,'Theft took place at 12:14. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (115,2020,8,22,'Expired parking meter took place at 22:17. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (116,2020,8,23,'Money laundering took place at 13:05. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (117,2020,8,23,'Littering took place at 05:09. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (118,2020,8,24,'Burglary took place at 02:13. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (119,2020,8,24,'Jaywalking took place at 13:18. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (120,2020,8,25,'Burglary took place at 07:21. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (121,2020,8,25,'Theft took place at 23:17. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (122,2020,8,27,'Burglary took place at 09:25. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (123,2020,8,28,'Burglary took place at 09:19. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (124,2020,9,1,'Theft took place at 01:06. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (125,2020,9,2,'Credit card fraud took place at 08:24. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (126,2020,9,3,'Jaywalking took place at 03:54. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (127,2020,9,3,'Money laundering took place at 10:24. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (128,2020,9,4,'Expired parking meter took place at 03:17. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (129,2020,9,4,'Vandalism took place at 21:22. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (130,2020,9,6,'Vandalism took place at 11:49. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (131,2020,9,12,'Burglary took place at 08:27. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (132,2020,9,12,'Credit card fraud took place at 18:03. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (133,2020,9,13,'Insider trading took place at 01:41. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (134,2020,9,13,'Insider trading took place at 04:28. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (135,2020,9,14,'Money laundering took place at 02:27. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (136,2020,9,14,'Littering took place at 21:47. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (137,2020,9,17,'Insider trading took place at 12:58. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (138,2020,9,19,'Expired parking meter took place at 13:25. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (139,2020,9,20,'Expired parking meter took place at 11:05. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (140,2020,9,20,'Burglary took place at 10:14. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (141,2020,9,21,'Forgery took place at 04:54. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (142,2020,9,22,'Reckless driving took place at 15:51. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (143,2020,9,24,'Bank robbery took place at 07:40. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (144,2020,9,24,'Bank robbery took place at 00:13. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (145,2020,9,26,'Reckless driving took place at 15:56. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (146,2020,9,27,'Bank robbery took place at 17:43. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (147,2020,9,27,'Insider trading took place at 23:06. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (148,2020,9,27,'Shoplifting took place at 16:40. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (149,2020,9,28,'Forgery took place at 08:13. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (150,2020,10,1,'Jaywalking took place at 23:21. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (151,2020,10,1,'Reckless driving took place at 03:03. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (152,2020,10,1,'Shoplifting took place at 04:38. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (153,2020,10,2,'Expired parking meter took place at 06:13. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (154,2020,10,3,'Expired parking meter took place at 01:42. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (155,2020,10,3,'Theft took place at 06:38. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (156,2020,10,5,'Reckless driving took place at 20:00. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (157,2020,10,6,'Jaywalking took place at 06:52. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (158,2020,10,7,'Credit card fraud took place at 05:46. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (159,2020,10,8,'Vandalism took place at 13:08. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (160,2020,10,9,'Littering took place at 15:40. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (161,2020,10,9,'Expired parking meter took place at 08:03. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (162,2020,10,10,'Vandalism took place at 12:37. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (163,2020,10,10,'Money laundering took place at 18:24. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (164,2020,10,11,'Reckless driving took place at 05:43. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (165,2020,10,12,'Shoplifting took place at 04:15. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (166,2020,10,13,'Reckless driving took place at 11:29. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (167,2020,10,13,'Reckless driving took place at 07:46. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (168,2020,10,14,'Credit card fraud took place at 21:14. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (169,2020,10,14,'Jaywalking took place at 21:07. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (170,2020,10,16,'Forgery took place at 15:22. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (171,2020,10,16,'Expired parking meter took place at 12:04. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (172,2020,10,17,'Insider trading took place at 01:40. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (173,2020,10,17,'Jaywalking took place at 08:03. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (174,2020,10,17,'Vandalism took place at 15:17. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (175,2020,10,19,'Wire fraud took place at 13:56. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (176,2020,10,20,'Credit card fraud took place at 07:59. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (177,2020,10,20,'Insider trading took place at 06:41. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (178,2020,10,21,'Shoplifting took place at 17:39. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (179,2020,10,22,'Jaywalking took place at 09:14. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (180,2020,10,22,'Burglary took place at 01:54. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (181,2020,10,22,'Bank robbery took place at 18:53. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (182,2020,10,23,'Theft took place at 10:46. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (183,2020,10,24,'Littering took place at 11:32. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (184,2020,10,24,'Burglary took place at 19:01. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (185,2020,10,27,'Shoplifting took place at 06:55. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (186,2020,10,27,'Insider trading took place at 14:36. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (187,2020,10,28,'Theft took place at 23:50. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (188,2020,10,28,'Theft took place at 22:40. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (189,2020,10,28,'Theft took place at 10:02. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (190,2020,11,1,'Littering took place at 13:27. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (191,2020,11,1,'Wire fraud took place at 17:10. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (192,2020,11,1,'Theft took place at 15:04. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (193,2020,11,1,'Vandalism took place at 20:09. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (194,2020,11,1,'Money laundering took place at 06:41. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (195,2020,11,2,'Reckless driving took place at 14:28. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (196,2020,11,4,'Burglary took place at 20:26. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (197,2020,11,5,'Reckless driving took place at 07:33. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (198,2020,11,5,'Insider trading took place at 02:14. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (199,2020,11,5,'Littering took place at 05:40. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (200,2020,11,5,'Reckless driving took place at 23:18. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (201,2020,11,6,'Burglary took place at 01:31. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (202,2020,11,8,'Forgery took place at 07:27. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (203,2020,11,8,'Insider trading took place at 00:18. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (204,2020,11,8,'Jaywalking took place at 01:39. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (205,2020,11,9,'Vandalism took place at 08:25. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (206,2020,11,11,'Shoplifting took place at 01:48. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (207,2020,11,11,'Littering took place at 18:16. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (208,2020,11,12,'Reckless driving took place at 18:32. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (209,2020,11,12,'Credit card fraud took place at 04:31. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (210,2020,11,13,'Reckless driving took place at 09:34. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (211,2020,11,13,'Reckless driving took place at 09:00. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (212,2020,11,14,'Credit card fraud took place at 14:17. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (213,2020,11,14,'Shoplifting took place at 17:05. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (214,2020,11,16,'Littering took place at 18:33. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (215,2020,11,16,'Jaywalking took place at 14:08. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (216,2020,11,16,'Credit card fraud took place at 16:09. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (217,2020,11,18,'Shoplifting took place at 03:02. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (218,2020,11,18,'Expired parking meter took place at 14:03. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (219,2020,11,19,'Wire fraud took place at 02:57. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (220,2020,11,19,'Forgery took place at 09:37. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (221,2020,11,20,'Vandalism took place at 22:08. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (222,2020,11,20,'Shoplifting took place at 21:01. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (223,2020,11,20,'Credit card fraud took place at 05:16. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (224,2020,11,20,'Burglary took place at 09:09. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (225,2020,11,20,'Bank robbery took place at 23:14. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (226,2020,11,20,'Expired parking meter took place at 14:06. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (227,2020,11,21,'Money laundering took place at 00:25. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (228,2020,11,22,'Forgery took place at 08:14. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (229,2020,11,22,'Bank robbery took place at 01:09. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (230,2020,11,22,'Wire fraud took place at 18:41. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (231,2020,11,22,'Burglary took place at 23:48. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (232,2020,11,23,'Littering took place at 17:48. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (233,2020,11,24,'Reckless driving took place at 20:55. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (234,2020,11,25,'Burglary took place at 20:25. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (235,2020,11,25,'Shoplifting took place at 19:17. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (236,2020,11,26,'Reckless driving took place at 01:45. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (237,2020,11,26,'Jaywalking took place at 17:02. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (238,2020,11,27,'Vandalism took place at 06:37. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (239,2020,11,28,'Vandalism took place at 09:45. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (240,2020,11,28,'Expired parking meter took place at 13:44. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (241,2020,12,1,'Vandalism took place at 18:46. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (242,2020,12,1,'Insider trading took place at 15:44. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (243,2020,12,1,'Wire fraud took place at 07:41. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (244,2020,12,1,'Shoplifting took place at 12:04. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (245,2020,12,2,'Bank robbery took place at 04:36. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (246,2020,12,2,'Credit card fraud took place at 10:54. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (247,2020,12,3,'Credit card fraud took place at 02:10. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (248,2020,12,3,'Bank robbery took place at 15:10. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (249,2020,12,4,'Expired parking meter took place at 11:46. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (250,2020,12,4,'Theft took place at 17:00. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (251,2020,12,4,'Jaywalking took place at 18:14. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (252,2020,12,4,'Forgery took place at 19:46. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (253,2020,12,5,'Bank robbery took place at 01:34. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (254,2020,12,6,'Shoplifting took place at 04:45. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (255,2020,12,6,'Bank robbery took place at 06:30. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (256,2020,12,6,'Vandalism took place at 14:48. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (257,2020,12,6,'Insider trading took place at 22:18. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (258,2020,12,6,'Jaywalking took place at 10:35. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (259,2020,12,7,'Theft took place at 01:44. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (260,2020,12,7,'Vandalism took place at 09:20. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (261,2020,12,7,'Insider trading took place at 01:07. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (262,2020,12,7,'Expired parking meter took place at 10:04. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (263,2020,12,7,'Reckless driving took place at 20:43. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (264,2020,12,7,'Wire fraud took place at 14:36. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (265,2020,12,8,'Littering took place at 08:31. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (266,2020,12,8,'Jaywalking took place at 13:33. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (267,2020,12,8,'Jaywalking took place at 07:51. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (268,2020,12,8,'Wire fraud took place at 10:20. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (269,2020,12,9,'Burglary took place at 07:18. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (270,2020,12,9,'Jaywalking took place at 07:03. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (271,2020,12,10,'Reckless driving took place at 20:31. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (272,2020,12,10,'Credit card fraud took place at 10:46. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (273,2020,12,11,'Burglary took place at 11:43. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (274,2020,12,11,'Expired parking meter took place at 15:55. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (275,2020,12,11,'Wire fraud took place at 17:16. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (276,2020,12,12,'Vandalism took place at 21:09. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (277,2020,12,12,'Bank robbery took place at 22:33. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (278,2020,12,13,'Theft took place at 21:21. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (279,2020,12,13,'Expired parking meter took place at 19:39. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (280,2020,12,14,'Burglary took place at 21:54. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (281,2020,12,14,'Expired parking meter took place at 14:59. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (282,2020,12,15,'Bank robbery took place at 07:16. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (283,2020,12,15,'Insider trading took place at 18:58. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (284,2020,12,16,'Burglary took place at 12:03. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (285,2020,12,16,'Money laundering took place at 10:30. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (286,2020,12,18,'Expired parking meter took place at 06:24. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (287,2020,12,18,'Credit card fraud took place at 18:10. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (288,2020,12,19,'Jaywalking took place at 05:27. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (289,2020,12,19,'Expired parking meter took place at 10:36. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (290,2020,12,20,'Money laundering took place at 17:47. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (291,2020,12,20,'Wire fraud took place at 23:58. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (292,2020,12,20,'Shoplifting took place at 05:51. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (293,2020,12,21,'Vandalism took place at 12:04. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (294,2020,12,21,'Shoplifting took place at 03:01. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (295,2020,12,21,'Theft of Pauline''s Mac took place at 10:15am at LePont. Interviews were conducted today with three witnesses who were present at the time — each of their interview transcripts mentions LePont.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (296,2020,12,21,'Money laundering took place at 20:30. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (297,2020,12,21,'Littering took place at 16:36. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (298,2020,12,22,'Insider trading took place at 06:35. One person witnessed the incident.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (299,2020,12,23,'Littering took place at 17:49. Two people witnessed the event.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (300,2020,12,24,'Bank robbery took place at 12:24. No known witnesses.');
INSERT INTO crime_scene_reports(id,year,month,day,description) VALUES (301,2021,1,1,'Vandalism took place at 13:52. One person witnessed the incident.');
